#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    Arm,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    little,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Conveyorbot - Remote Control
- NOTE: Conveyorbot can be used to pick up 4 of the game objects with its intake and score them
anywhere on the field.
- This program allows you to remotely control your robot using the USB Logitech Joysticks.
- This program also ignores low values that would cause your robot to move when the joysticks fail to
return back to exact center.  You may need to adjust the 'threshold' value to get it just right.

Robot Model(s): TETRIX Conveyorbot (Virtual Worlds)
[I/O Port]          [Name]              [Type]                [Description]
Motor Port D        rightMotor          TETRIX Motor          Right side motor
Motor Port E				leftMotor						TETRIX Motor					Left side motor
Motor Port F 				armMotor						TETRIX Motor					Arm motor

Motor Port G 				intakeMotor					TETRIX Motor 					Intake motor

Sensor Port 2				gyro								HiTechnic Gyro				HiTechnic Gyro
Sensor Port 3				light   						Light Sensor					NXT Light Sensor (Active)
Sensor Port 4				sonar 							Sonar Sensor					NXT Sonar Sensor
----------------------------------------------------------------------------------------------------*/

#pragma debuggerWindows("joystickSimple");
#include "JoystickDriver.c"

task tube(){
	while (true){

	}
}


task main()
//Integer variable that allows you to specify a "deadzone" where values (both positive or negative)
//less than the threshold will be ignored.
{
	int threshold = 0;
	int little = 0;

	//set grabber to start position
	servo [Arm]=0;
	while(1 == 1) //Loop Forever
		//Get the Latest joystick values
	{
		getJoystickSettings(joystick);


		if(joy1Btn(7)) {
			motor[rightMotor] = (joystick.joy1_y2);
			motor[leftMotor] = (joystick.joy1_y1);
	  } else {
			motor[rightMotor] = ((joystick.joy1_y2))/3;
			motor[leftMotor] = ((joystick.joy1_y1))/3;
		}

		if (joy1Btn(1) &&   little == 0 )// if you hit it and the grabber is up , take it down
		{
			little = 1;  //toggled down
			servo [Arm] = 175;
			wait1Msec(500);
		}

		else if (joy1Btn(1)&& little ==1)
		{
			little = 0; // toggle up
			servo[Arm]=0;
			wait1Msec(500);
		}

	}
}
